<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TagSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $tags = [
            "Artificial Intelligence",
            "Blockchain",
            "Machine Learning",
            "Internet of Things",
            "Cybersecurity",
            "Biotechnology",
            "Robotics",
            "Data Science",
            "Virtual Reality",
            "Augmented Reality",
            "Fitness",
            "Nutrition",
            "Mental Health",
            "Yoga",
            "Meditation",
            "Healthy Eating",
            "Weight Loss",
            "Alternative Medicine",
            "Stress Management",
            "Self-Care",
            "Startup",
            "Leadership",
            "Marketing",
            "Sales",
            "Finance",
            "E-commerce",
            "Business Strategy",
            "Productivity",
            "Management",
            "Networking",
            "Government",
            "Political News",
            "International Relations",
            "Public Policy",
            "Democracy",
            "Human Rights",
            "Political Parties",
            "Elections",
            "Social Issues",
            "Political Analysis",
            "Fine Arts",
            "Music",
            "Film",
            "Literature",
            "Theater",
            "Photography",
            "Sculpture",
            "Cultural Heritage",
            "Art History",
            "Contemporary Art",
            "Football",
            "Basketball",
            "Baseball",
            "Soccer",
            "Tennis",
            "Fitness Training",
            "Athletics",
            "Yoga",
            "Sports Nutrition",
            "Sports Psychology",
            "Adventure Travel",
            "Backpacking",
            "Beach Holidays",
            "City Breaks",
            "Cultural Experiences",
            "Hiking",
            "Solo Travel",
            "Food Tourism",
            "Nature Exploration",
            "Travel Tips",
            "Recipes",
            "Baking",
            "Vegetarian",
            "Vegan",
            "Healthy Eating",
            "Culinary Techniques",
            "Gourmet",
            "Food Photography",
            "Restaurant Reviews",
            "International Cuisine",
            "Fashion Trends",
            "Street Style",
            "Designer Brands",
            "Fashion Week",
            "Beauty",
            "Personal Style",
            "Accessories",
            "Fashion Tips",
            "Sustainable Fashion",
            "Celebrity Fashion",
            "Online Learning",
            "Study Tips",
            "Educational Technology",
            "Language Learning",
            "Higher Education",
            "Skill Development",
            "STEM Education",
            "Distance Learning",
            "Educational Resources",
            "Lifelong Learning",
            "Climate Change",
            "Renewable Energy",
            "Conservation",
            "Sustainable Living",
            "Green Technology",
            "Eco-Friendly Products",
            "Environmental Activism",
            "Waste Management",
            "Biodiversity",
            "Carbon Footprint",
            "Budgeting",
            "Investment Strategies",
            "Retirement Planning",
            "Financial Independence",
            "Stock Market",
            "Cryptocurrency",
            "Tax Planning",
            "Wealth Management",
            "Credit Management",
            "Real Estate Investing",
            "Pregnancy",
            "Newborn Care",
            "Parenting Tips",
            "Child Development",
            "Education",
            "Family Activities",
            "Parenting Styles",
            "Parenting Challenges",
            "Single Parenting",
            "Blended Families",
            "Dating Advice",
            "Marriage",
            "Love and Romance",
            "Communication",
            "Intimacy",
            "Relationship Problems",
            "Breakups",
            "Online Dating",
            "Long-Distance Relationships",
            "Other Relationships",
            "Goal Setting",
            "Time Management",
            "Motivation",
            "Personal Development",
            "Habit Formation",
            "Mindfulness",
            "Productivity Tools",
            "Self-Reflection",
            "Success Strategies",
            "Stress Reduction",
            "Ancient Civilizations",
            "World History",
            "Archaeological Discoveries",
            "Historical Events",
            "Historical Figures",
            "Military History",
            "Cultural History",
            "Historical Sites",
            "Historical Research",
            "Archival Studies",
            "Psychological Disorders",
            "Therapy",
            "Cognitive Behavioral Therapy",
            "Mindfulness",
            "Emotional Well-being",
            "Stress Management",
            "Positive Psychology",
            "Mental Health Awareness",
            "Self-Care",
            "Psychological Research",
            "Movies",
            "TV Shows",
            "Celebrity News",
            "Music",
            "Books",
            "Gaming",
            "Pop Music",
            "Celebrity Interviews",
            "Film Reviews",
            "Entertainment Industry",
            "Interior Decorating",
            "Home Renovation",
            "Home Organization",
            "DIY Projects",
            "Home Styling",
            "Furniture",
            "Home Improvement",
            "Color Schemes",
            "Home Accessories",
            "Space Planning",
            "Craft Ideas",
            "DIY Home Decor",
            "Upcycling",
            "Knitting",
            "Crocheting",
            "Sewing",
            "Paper Crafts",
            "Jewelry Making",
            "Woodworking",
            "DIY Gifts",
        ];
        
        foreach(array_unique($tags) as $tag) {
            \App\Models\Tag::factory()->create([
                "name" => $tag,
                "slug" => \Illuminate\Support\Str::slug($tag)
            ]);
        }
    }
}
